

library(impute)       #knn imputation of missing values
library(Biobase)

#Paleta de colores
numColores=255*2
gvect=c(array(255:0),array(0,dim=255))
rvect=c(array(0,dim=255),array(0:255))
bvect=array(0,dim=numColores)
paleta=rgb(rvect, gvect, bvect, 255, maxColorValue=255)

#Opciones de visualización
library(grid)
oldpar=par()
par(mai=c(0,0,0,0),mar=c(0,0,0,0))

# --- Yeast (Saccharomyces Cerevisiae) Data ---
# From http://rana.lbl.gov/EisenData.htm
# 6221x80 matrix
# Yaa111a  notation (ORF - Open Reading Frame).
Adata=read.exprSet("EisenYeastData.txt")
Acar=(exprs(Adata))
n=dim(Acar)[1]
m=dim(Acar)[2]-1
Aeisen=matrix(as.numeric(Acar[,1:m+1]),n,m)
arrayNamesEisen=sampleNames(Adata)[1:m+1]
geneNamesEisen=Acar[1:n,1]
#Aeisen=impute.knn(Aeisen)
image(1:m,1:n, t(Aeisen),col=paleta, axes=FALSE, main="Eisen Yeast Data")


# --- Bicat Example 1 ---
# Supposedly a simplified yeast microarray with the most expressed genes
# From http://www.tik.ee.ethz.ch/sop/bicat/
# 419x70 matrix
# nnnnnn_at  notation (Affymetrix notation for probe sets).
Adata=read.exprSet("dataSample_1BicAT.txt")
Acar=(exprs(Adata))
n=dim(Acar)[1]
m=dim(Acar)[2]-1
Abicat=matrix(as.numeric(Acar[,1:m+1]),n,m)
arrayNamesBicat=sampleNames(Adata)[1:m+1]
geneNamesBicat=Acar[1:n,1]
image(1:m,1:n, t(Abicat),col=paleta, axes=FALSE, main="BicAT Example 1")


# --- Escherichia Coli synthetic data ---
# Microarray Data generated by SynTRen for 200 E. coli genes and 20 experiments
# 200x20 matrix
# nnnnnn_at  notation (Affymetrix notation for probe sets).
Adata=read.exprSet("Ecoli200.txt")
Acar=(exprs(Adata))
n=dim(Acar)[1]
m=dim(Acar)[2]-1
Asyntren=matrix(as.numeric(Acar[,1:m+1]),n,m)
Asyntren=impute.knn(Asyntren)
arrayNamesSyntren=sampleNames(Adata)[1:m+1]
geneNamesSyntren=Acar[1:n,1]
image(1:m,1:n, t(Asyntren),col=paleta, axes=FALSE, main="Synthetic E. coli")
